apiVersion: v1
kind: Secret
metadata:
  name: {{ include "repaircafe.appSecretName" . }}
  labels:
    {{- include "repaircafe.labels" . | nindent 4 }}
type: Opaque
stringData:
  sessionSecret: {{ .Values.app.sessionSecret | quote }}
